### ISSUE TITLE
fedora download through cdi takes too long

### ISSUE THREAD

**Issue by karmab** [scollier/kubevirt-tutorial#31]
we should either use a lighter image or use uploader to use a prefetched and local image

**Comment by StLuke** [comment]
First run -> Segmentation fault

E1011 13:45:34.502150       1 prlimit.go:143] qemu-img [convert -p -f qcow2 -O raw json: {"file.driver": "https", "file.url": "https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2", "file.timeout": 3600} /data/disk.img] failed output is:E1011 13:45:34.503582       1 prlimit.go:144]     (0.00/100%)    (1.01/100%)    (2.01/100%)    (3.02/100%)    (4.02/100%)E1011 13:45:34.503723       1 importer.go:40] signal: segmentation fault 

Second run stuck on 87%

**Comment by karmab** [comment]
addressed in https://github.com/scollier/kubevirt-tutorial/commit/13bd8583b657107d7a9bd9b3f41d23f6a873399d
