### ISSUE TITLE
Routes and wild card dns

### ISSUE THREAD

**Issue by jcpowermac** [scollier/kubevirt-tutorial#6]

**Comment by karmab** [comment]
fixed by:
- adding kcli support of wildcard dns in gcp (https://github.com/karmab/kcli/commit/49c61ddf65d69bd2d25589522978a9ee15454cf2)
- making sure the plan makes use of it ( uses alias: [*'] in vm definition)

**Comment by karmab** [comment]
also added full dns support on aws provider....
