### ISSUE TITLE
expose vm via ssh

### ISSUE THREAD

**Issue by jcpowermac** [scollier/kubevirt-tutorial#9]

**Comment by karmab** [comment]
a couple of virtctl expose should do the trick actually

**Comment by karmab** [comment]
added port 27017 to the existing firewall rule on our cnvlab gcp project (matches all instances created with the cnvlab tag)

**Comment by karmab** [comment]
addressed by https://github.com/scollier/kubevirt-tutorial/pull/28
(using port 30000 instead which was opened on the firewall rules for the cnvlab tag
